/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { LendingPoolParametersProvider } from "../LendingPoolParametersProvider";

export class LendingPoolParametersProviderFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<LendingPoolParametersProvider> {
    return super.deploy(
      overrides || {}
    ) as Promise<LendingPoolParametersProvider>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): LendingPoolParametersProvider {
    return super.attach(address) as LendingPoolParametersProvider;
  }
  connect(signer: Signer): LendingPoolParametersProviderFactory {
    return super.connect(signer) as LendingPoolParametersProviderFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LendingPoolParametersProvider {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as LendingPoolParametersProvider;
  }
}

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "getMaxStableRateBorrowSizePercent",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "pure",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "getRebalanceDownRateDelta",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50609e8061001e6000396000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c806346f4f8d1146037578063d6b725ac14604f575b600080fd5b603d6055565b60408051918252519081900360200190f35b603d6064565b6aa56fa5b99019a5c800000090565b60199056fea265627a7a72315820b7672cc5059b7ff68edfc802cb7c11b76ab2153ff138ffe50233defbd5b2423d64736f6c63430005110032";
