/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import { LendingPoolParametersProvider } from "./LendingPoolParametersProvider";

export class LendingPoolParametersProviderFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<LendingPoolParametersProvider> {
    return super.deploy(overrides || {}) as Promise<
      LendingPoolParametersProvider
    >;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): LendingPoolParametersProvider {
    return super.attach(address) as LendingPoolParametersProvider;
  }
  connect(signer: Signer): LendingPoolParametersProviderFactory {
    return super.connect(signer) as LendingPoolParametersProviderFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LendingPoolParametersProvider {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as LendingPoolParametersProvider;
  }
}

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "getMaxStableRateBorrowSizePercent",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: true,
    inputs: [],
    name: "getRebalanceDownRateDelta",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  }
];

const _bytecode =
  "0x608060405260196000556aa56fa5b99019a5c800000060015534801561002457600080fd5b5060b7806100336000396000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c806346f4f8d1146037578063d6b725ac146053575b600080fd5b603d606f565b6040518082815260200191505060405180910390f35b60596079565b6040518082815260200191505060405180910390f35b6000600154905090565b6000805490509056fea265627a7a72315820cd6885708abdf044a857a509720127f569ad8cf83c316a660d3a821fa0533cba64736f6c63430005100032";
