/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface UintStorageInterface extends ethers.utils.Interface {
  functions: {
    "getUint(bytes32)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "getUint", values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: "getUint", data: BytesLike): Result;

  events: {};
}

export class UintStorage extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: UintStorageInterface;

  functions: {
    /**
     * function to return the uint associated with a given key value
     * @param _key the key value to be examined*
     */
    getUint(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;
  };

  /**
   * function to return the uint associated with a given key value
   * @param _key the key value to be examined*
   */
  getUint(_key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

  staticCall: {
    /**
     * function to return the uint associated with a given key value
     * @param _key the key value to be examined*
     */
    getUint(_key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    getUint(_key: BytesLike): Promise<BigNumber>;
  };

  populateTransaction: {
    getUint(_key: BytesLike): Promise<PopulatedTransaction>;
  };
}
